version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - whoami1
      - whoami2
      - whoami3

  whoami1:
    image: traefik/whoami
    ports:
      - "801:80"

  whoami2:
    image: traefik/whoami
    ports:
      - "802:80"

  whoami3:
    image: traefik/whoami
    ports:
      - "803:80"
